services:

  postgres:
    image: postgres:16
    container_name: bank_rest_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: bank_rest
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d bank_rest"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_rest_app
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_rest
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: bank_password
    ports:
      - "8080:8080"

volumes:
  postgres_data: